
import student_model.Student;
import student_utils.StudentManager;
import student_view.StudentTable;

/**
 *
 * @author ASUS
 */
public class AddStudent extends javax.swing.JFrame {
    
    public AddStudent(StudentTable studentTableReference) {
        initComponents();
        
    }

    /**
     * Creates new form addStudent
     */
    public AddStudent() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.maleIconLabel.setVisible(false);
        this.femaleIconLabel.setVisible(false);
        this.departmentLabel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        idLabel = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        birthdayLabel = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();
        dayTF = new javax.swing.JTextField();
        monthLabel = new javax.swing.JLabel();
        monthTF = new javax.swing.JTextField();
        yearLabel = new javax.swing.JLabel();
        yearTF = new javax.swing.JTextField();
        hometownLabel = new javax.swing.JLabel();
        hometownTF = new javax.swing.JTextField();
        departmentLabel = new javax.swing.JLabel();
        departmentTF = new javax.swing.JTextField();
        schoolyearLabel = new javax.swing.JLabel();
        schoolyearTF = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        maleIconLabel = new javax.swing.JLabel();
        femaleIconLabel = new javax.swing.JLabel();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        defaultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idLabel.setText("Student ID");
        getContentPane().add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 14, 65, -1));
        getContentPane().add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 9, 280, -1));

        nameLabel.setText("Name");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 53, 65, -1));
        getContentPane().add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 53, 280, -1));

        birthdayLabel.setText("Birth Day:");
        getContentPane().add(birthdayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 98, -1, -1));

        dayLabel.setText("Day");
        getContentPane().add(dayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 98, 37, -1));
        getContentPane().add(dayTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 93, 50, -1));

        monthLabel.setText("Month");
        getContentPane().add(monthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 98, 37, -1));
        getContentPane().add(monthTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 93, 43, -1));

        yearLabel.setText("Year");
        getContentPane().add(yearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 98, 33, -1));
        getContentPane().add(yearTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 93, 80, -1));

        hometownLabel.setText("Home town");
        getContentPane().add(hometownLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 145, 64, -1));
        getContentPane().add(hometownTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 140, 280, -1));

        departmentLabel.setText("Department");
        getContentPane().add(departmentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 189, -1, -1));
        getContentPane().add(departmentTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 120, -1));

        schoolyearLabel.setText("Shool year");
        getContentPane().add(schoolyearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));
        getContentPane().add(schoolyearTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 75, -1));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        maleIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-male-96.png"))); // NOI18N
        getContentPane().add(maleIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 100));

        femaleIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-female-96.png"))); // NOI18N
        getContentPane().add(femaleIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 100));

        buttonGroup1.add(maleButton);
        maleButton.setText("male");
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(maleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        buttonGroup1.add(femaleButton);
        femaleButton.setText("female");
        femaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(femaleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        defaultLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-avatar-96.png"))); // NOI18N
        getContentPane().add(defaultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String ID = idTF.getText().toString();
        String name = nameTF.getText().toString();
        int day = Integer.parseInt(dayTF.getText().toString());
        int month = Integer.parseInt(monthTF.getText().toString());
        int year = Integer.parseInt(yearTF.getText().toString());
        String hometown = hometownTF.getText().toString();
        String department = departmentTF.getText().toString();
        String schoolyear = schoolyearTF.getText().toString();
        StudentManager.List_Of_Student.add(new Student(ID, name, "null", day, month, year, department, schoolyear, hometown));
    }//GEN-LAST:event_addButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        idTF.setText("");
        nameTF.setText("");
        dayTF.setText("");
        monthTF.setText("");
        yearTF.setText("");
        departmentTF.setText("");
        hometownTF.setText("");
        schoolyearTF.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
        // TODO add your handling code here:
        this.maleIconLabel.setVisible(true);
        this.femaleIconLabel.setVisible(false);
        this.defaultLabel.setVisible(false);

    }//GEN-LAST:event_maleButtonActionPerformed

    private void femaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleButtonActionPerformed
        // TODO add your handling code here:
        this.maleIconLabel.setVisible(false);
        this.femaleIconLabel.setVisible(true);
        this.defaultLabel.setVisible(false);
    }//GEN-LAST:event_femaleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JTextField dayTF;
    private javax.swing.JLabel defaultLabel;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JTextField departmentTF;
    private javax.swing.JButton exitButton;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JLabel femaleIconLabel;
    private javax.swing.JLabel hometownLabel;
    private javax.swing.JTextField hometownTF;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTF;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JLabel maleIconLabel;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JTextField monthTF;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel schoolyearLabel;
    private javax.swing.JTextField schoolyearTF;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTF;
    // End of variables declaration//GEN-END:variables
}
