/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student_view;

/**
 *
 * @author ASUS
 */
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import student_model.Student;
import student_utils.StudentManager;
import subjectView.*;

public class UpdateStudent extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStudent
     */
    public UpdateStudent() {

        initComponents();
        this.setLocationRelativeTo(null);
        Student currentStudent = StudentManager.List_Of_Student.get(StudentManager.studentPosition);
        idTF.setText(currentStudent.getStudentID());
        nameTF.setText(currentStudent.getName());
        if (currentStudent.getGender().equalsIgnoreCase("male")) {
            maleButton.doClick();;

            this.maleIconLabel.setVisible(true);
            this.femaleIconLabel.setVisible(false);
            this.defaultLabel.setVisible(false);
        } else if (StudentManager.List_Of_Student.get(StudentManager.studentPosition).getGender().equalsIgnoreCase("female")) {
            femaleButton.doClick();
            this.maleIconLabel.setVisible(false);
            this.femaleIconLabel.setVisible(true);
            this.defaultLabel.setVisible(false);
        }
        yearComboBox.setSelectedIndex(currentStudent.getYearOfBirth() - 1924);
        monthComboBox.setSelectedIndex(currentStudent.getMonthOfBirth() - 1);
        dayComboBox.setSelectedIndex(currentStudent.getDayOfBirth() - 1);

        departmentTF.setText(currentStudent.getDepartment());
        schoolyearTF.setText(currentStudent.getSchoolYear());
        hometownTF.setText(currentStudent.getHometown());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        updatePanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        birthdayLabel = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();
        monthLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        hometownLabel = new javax.swing.JLabel();
        hometownTF = new javax.swing.JTextField();
        departmentLabel = new javax.swing.JLabel();
        departmentTF = new javax.swing.JTextField();
        schoolyearLabel = new javax.swing.JLabel();
        schoolyearTF = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        femaleIconLabel = new javax.swing.JLabel();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        defaultLabel = new javax.swing.JLabel();
        maleIconLabel = new javax.swing.JLabel();
        dayComboBox = new javax.swing.JComboBox<>();
        monthComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new javax.swing.JComboBox<>();
        manageSubject = new javax.swing.JToggleButton();
        mainTextPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        updatePanel.setBackground(new java.awt.Color(255, 247, 212));
        updatePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idLabel.setText("Student ID");
        updatePanel.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 14, 65, -1));

        idTF.setEnabled(false);
        updatePanel.add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 9, 290, -1));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nameLabel.setText("Name");
        updatePanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 53, 65, -1));
        updatePanel.add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 53, 290, -1));

        birthdayLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        birthdayLabel.setText("Birth Day:");
        updatePanel.add(birthdayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 98, -1, -1));

        dayLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dayLabel.setText("Day");
        updatePanel.add(dayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 98, 37, -1));

        monthLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        monthLabel.setText("Month");
        updatePanel.add(monthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 98, 50, -1));

        yearLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        yearLabel.setText("Year");
        updatePanel.add(yearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 33, -1));

        hometownLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hometownLabel.setText("Home town");
        updatePanel.add(hometownLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 145, 90, -1));
        updatePanel.add(hometownTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 140, 290, -1));

        departmentLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        departmentLabel.setText("Department");
        updatePanel.add(departmentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 189, -1, -1));
        updatePanel.add(departmentTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 120, -1));

        schoolyearLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        schoolyearLabel.setText("Shool year");
        updatePanel.add(schoolyearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));
        updatePanel.add(schoolyearTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 90, -1));

        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateButton.setText("Update");
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        updatePanel.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        clearButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearButton.setText("Clear");
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        updatePanel.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitButton.setText("Exit");
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        updatePanel.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        femaleIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-female-96.png"))); // NOI18N
        updatePanel.add(femaleIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 100));

        buttonGroup1.add(maleButton);
        maleButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maleButton.setText("male");
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });
        updatePanel.add(maleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        buttonGroup1.add(femaleButton);
        femaleButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        femaleButton.setText("female");
        femaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleButtonActionPerformed(evt);
            }
        });
        updatePanel.add(femaleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        defaultLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-avatar-96.png"))); // NOI18N
        updatePanel.add(defaultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 100));

        maleIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-male-96.png"))); // NOI18N
        updatePanel.add(maleIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        dayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dayComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dayComboBoxItemStateChanged(evt);
            }
        });
        dayComboBox.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dayComboBoxMouseMoved(evt);
            }
        });
        updatePanel.add(dayComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        monthComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        monthComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthComboBoxItemStateChanged(evt);
            }
        });
        monthComboBox.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                monthComboBoxMouseMoved(evt);
            }
        });
        updatePanel.add(monthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));
        yearComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yearComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearComboBoxItemStateChanged(evt);
            }
        });
        yearComboBox.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                yearComboBoxMouseMoved(evt);
            }
        });
        updatePanel.add(yearComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        manageSubject.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manageSubject.setText("Manage Subject");
        manageSubject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSubjectActionPerformed(evt);
            }
        });
        updatePanel.add(manageSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Student Information");
        mainTextPanel.add(jLabel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
            .addComponent(mainTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:

        String ID = idTF.getText().toString();
        String name = nameTF.getText().toString();
        int day = (dayComboBox.getSelectedIndex() + 1);
        int month = (monthComboBox.getSelectedIndex() + 1);
        int year = Integer.parseInt(yearComboBox.getSelectedItem().toString());
//        int day = Integer.parseInt(dayTF.getText().toString());
//        int month = Integer.parseInt(monthTF.getText().toString());
//        int year = Integer.parseInt(yearTF.getText().toString());
        String hometown = hometownTF.getText().toString();
        String department = departmentTF.getText().toString();
        String schoolyear = schoolyearTF.getText().toString();

        StudentManager.List_Of_Student.get(StudentManager.studentPosition).setStudentID(ID);
        StudentManager.List_Of_Student.get(StudentManager.studentPosition).setName(name);
        if (maleButton.isSelected()) {
            StudentManager.List_Of_Student.get(StudentManager.studentPosition).setGender("male");
        } else if (femaleButton.isSelected()) {
            StudentManager.List_Of_Student.get(StudentManager.studentPosition).setGender("female");
        }

        StudentManager.List_Of_Student.get(StudentManager.studentPosition).setDayOfBirth(day);
        StudentManager.List_Of_Student.get(StudentManager.studentPosition).setMonthOfBirth(month);
        StudentManager.List_Of_Student.get(StudentManager.studentPosition).setYearOfBirth(year);
        StudentManager.List_Of_Student.get(StudentManager.studentPosition).setDepartment(department);
        StudentManager.List_Of_Student.get(StudentManager.studentPosition).setAddress(hometown);
        StudentManager.List_Of_Student.get(StudentManager.studentPosition).setSchoolYear(schoolyear);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        idTF.setText("");
        nameTF.setText("");
        maleButton.isSelected();
        dayComboBox.setSelectedIndex(0);
        monthComboBox.setSelectedIndex(0);
        yearComboBox.setSelectedIndex(0);
        departmentTF.setText("");
        hometownTF.setText("");
        schoolyearTF.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
        // TODO add your handling code here:
        this.maleIconLabel.setVisible(true);
        this.femaleIconLabel.setVisible(false);
        this.defaultLabel.setVisible(false);
    }//GEN-LAST:event_maleButtonActionPerformed

    private void femaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleButtonActionPerformed
        // TODO add your handling code here:
        this.maleIconLabel.setVisible(false);
        this.femaleIconLabel.setVisible(true);
        this.defaultLabel.setVisible(false);
    }//GEN-LAST:event_femaleButtonActionPerformed

    private void dayComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dayComboBoxItemStateChanged

    }//GEN-LAST:event_dayComboBoxItemStateChanged

    private void dayComboBoxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dayComboBoxMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_dayComboBoxMouseMoved

    private void monthComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthComboBoxItemStateChanged
        // TODO add your handling code here:
        updateDayComboBox();
    }//GEN-LAST:event_monthComboBoxItemStateChanged

    private void monthComboBoxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthComboBoxMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_monthComboBoxMouseMoved

    private void yearComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearComboBoxItemStateChanged
        // TODO add your handling code here:
        updateDayComboBox();
    }//GEN-LAST:event_yearComboBoxItemStateChanged

    private void yearComboBoxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearComboBoxMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_yearComboBoxMouseMoved

    private void manageSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSubjectActionPerformed
        // TODO add your handling code here:
//        new studentSubjectFrame().setVisible(true);
        new StudentProcessSubject().setVisible(true);

    }//GEN-LAST:event_manageSubjectActionPerformed

    private void updateDayComboBox() {
        int selectedMonthIndex = monthComboBox.getSelectedIndex() + 1;
        int selectedYear = Integer.parseInt(yearComboBox.getSelectedItem().toString());
        int daysInMonth = getDaysInMonth(selectedMonthIndex, selectedYear);

        // Xóa các mục cũ và thêm các mục mới vào ComboBox ngày
        dayComboBox.removeAllItems();
        for (int i = 1; i <= daysInMonth; i++) {
            dayComboBox.addItem(String.valueOf(i));
        }
    }

    private int getDaysInMonth(int month, int year) {
        switch (month) {
            case 4:
            case 6:
            case 9:
            case 11:
                return 30;
            case 2:
                // Kiểm tra năm nhuận
                return (year % 4 == 0 && (year % 100 != 0 || year % 400 == 0)) ? 29 : 28;
            default:
                return 31;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> dayComboBox;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JLabel defaultLabel;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JTextField departmentTF;
    private javax.swing.JButton exitButton;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JLabel femaleIconLabel;
    private javax.swing.JLabel hometownLabel;
    private javax.swing.JTextField hometownTF;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainTextPanel;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JLabel maleIconLabel;
    private javax.swing.JToggleButton manageSubject;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel schoolyearLabel;
    private javax.swing.JTextField schoolyearTF;
    private javax.swing.JButton updateButton;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JComboBox<String> yearComboBox;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
